## Generate Embeddings

In [1]:
import pandas as pd

dataset = pd.read_csv("sentences.csv")
dataset.head(10)

                                            sentence
0       A little girl is smiling and running outside
1      A man is drawing on a digital dry erase board
2             A black bird is sitting on a dead tree
3               An elderly man is sitting on a bench
4  A man and a woman are sitting comfortably on t...
5             A sheepdog is grouping a herd of sheep
6  A man is opening a small package that contains...
7  The man in a t-shirt dyed grey is sitting on a...
8                  A woman is not slicing a cucumber
9  A purple crowd of people is eating on various ...

In [2]:
# if you are not gareeb like me, you can run this openai code, if you are
# then run the next cell.

# from openai import OpenAI

# client = OpenAI()


# def get_embedding(sentence):
#     return (
#         client.embeddings.create(input=sentence, model="text-embedding-3-small")
#         .data[0]
#         .embedding
#     )

In [3]:
# use this in case of hugging face interface
# import os

# import numpy as np
# from dotenv import load_dotenv
# from huggingface_hub import InferenceClient

# load_dotenv()  # loads HF_TOKEN from .env

# client = InferenceClient(
#     model="sentence-transformers/all-MiniLM-L6-v2",
#     token=os.getenv("HF_TOKEN"),
# )


# def get_embedding(sentence):
#     embedding = np.array(client.feature_extraction(sentence)).flatten()
#     embedding = embedding / np.linalg.norm(embedding)  # normalize, as OpenAI does
#     return embedding.tolist()

In [4]:
## this is for gemnin

import os

import numpy as np
from dotenv import load_dotenv
from google import genai
from google.genai import types

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

EMBEDDING_DIM = 768  # choose 768, 1536 or 3072


def get_embedding(sentence, task_type="SEMANTIC_SIMILARITY"):
    result = client.models.embed_content(
        model="gemini-embedding-001",
        contents=sentence,
        config=types.EmbedContentConfig(
            task_type=task_type,
            output_dimensionality=EMBEDDING_DIM,
        ),
    )
    vec = np.array(result.embeddings[0].values)
    return (vec / np.linalg.norm(vec)).tolist()  # normalize

In [5]:
import os
import numpy as np

if os.path.exists("embedded_sentences_.csv"):
    dataset = pd.read_csv("embedded_sentences.csv")
    dataset["embedding"] = dataset.embedding.apply(eval).apply(np.array)
else:
    dataset["embedding"] = dataset["sentence"].apply(get_embedding)
    dataset.to_csv("embedded_sentences_MALE.csv", index=False)

In [6]:
dataset["id"] = range(1, len(dataset) + 1)
dataset.head()

,sentence,embedding,id
0,A little girl is smiling and running outside,"[-0.027314407690614502, 0.02402331055773757, -...",1
1,A man is drawing on a digital dry erase board,"[-0.0428258120831992, 0.008480906063096276, 0....",2
2,A black bird is sitting on a dead tree,"[-0.0028641700818172536, 0.014019344986653314,...",3
3,An elderly man is sitting on a bench,"[-0.04732383053005765, -0.0021940971607502698,...",4
4,A man and a woman are sitting comfortably on t...,"[-0.04056476194830314, -0.004490521620387626, ...",5

In [7]:
embedding_dimension = len(dataset.iloc[0]["embedding"])
embedding_dimension

768

In [8]:
dataset['embedding'][0]

[-0.027314407690614502,
 0.02402331055773757,
 -0.0007406451834097945,
 -0.08604090789911192,
 -0.00583445131626445,
 0.013171032127197458,
 -0.03486287242299178,
 0.02603564661011978,
 0.017547701706453967,
 0.012428259793652639,
 0.041481543918935805,
 -0.0073304804238668655,
 -0.02113414839370148,
 0.05445098567106718,
 0.23973786039030096,
 0.023227088380582912,
 -0.0031932229340497775,
 0.024821902632451914,
 0.023271772002250543,
 -0.030714136266657473,
 -0.004614502422426217,
 -0.010935524723706755,
 0.001639925757427192,
 -0.003063072546867107,
 -0.01640134986994826,
 -0.020110554851758798,
 0.03429884537174626,
 -0.010389418416263976,
 0.021926216824157168,
 0.001131594383299633,
 -0.004510639905441381,
 0.011515051556157513,
 0.02399745074278949,
 -0.04224744408790636,
 -0.006161166970347056,
 -0.017470807698358726,
 0.06581749417303762,
 0.030063564257890734,
 0.037391741614280945,
 0.026720797189281942,
 -0.048307039099524565,
 -0.036043777126014816,
 0.0036488034386922964,
 -0.028593789091367082,
 0.02341756868274356,
 0.02508920240146134,
 -0.015784273441513515,
 -0.026202370531355854,
 0.015740201572144372,
 0.06973722591152938,
 -0.016521342427229052,
 0.0007117160512433442,
 -0.00808300429468059,
 -0.31769791112534856,
 0.01292918142516427,
 -0.005505763832014144,
 -0.05068175527955441,
 0.009126782749367152,
 0.015963626534850003,
 -0.019128529621459518,
 0.013521055543852415,
 0.0772806749604958,
 -0.03015863433497771,
 -0.03593025509164463,
 0.00041105127760260416,
 -0.032939531764508485,
 0.03758266316634876,
 -0.017217396591476006,
 -0.0029703896746177284,
 0.0468942682802319,
 0.025241909141180265,
 0.03214694754289917,
 0.04023041964816095,
 0.043161081580165545,
 0.0213091541044574,
 -0.025091514036897362,
 0.013493867695203138,
 0.024892039947793838,
 0.049075375996137836,
 0.0615601060104348,
 0.02608310625062088,
 -0.010954052935828292,
 0.016778901283239184,
 -0.025039081552782234,
 0.011281761959119395,
 0.004659247047964506,
 -0.07296721978541627,
 -0.02416188873246763,
 -0.002747095801690347,
 -0.01229597615594788,
 0.01711563750851468,
 -0.009770135738293372,
 -0.009330186618711909,
 0.014359747381975414,
 -0.01783561769928159,
 -0.011427637464838547,
 -0.013070262643542508,
 -0.0049627490156685635,
 0.019660264033867537,
 0.010275257897562092,
 -0.03914474952704465,
 -0.050976371416603564,
 -0.02266641996940753,
 0.001407859150908485,
 -0.01852669559273077,
 -0.038957945736246474,
 0.006418814076338626,
 -0.017621812841348245,
 -0.03627599624221018,
 0.03382408274832365,
 -0.023387739332222806,
 -0.012949597158733379,
 0.020869960507532533,
 0.011887457567132848,
 0.03398293271490553,
 -0.26911357173464656,
 0.01603892518891193,
 0.017718332617159365,
 -0.0422208097294319,
 0.01933878563062489,
 -0.013749210020126176,
 0.017364936851699306,
 0.0039460845538215735,
 0.04222305796196864,
 0.026221233750688466,
 0.003076781624565579,
 0.03898145964392109,
 -0.005471332630519757,
 0.01493789785743417,
 0.007317369732450275,
 0.03951959946274856,
 -0.007509975745328771,
 -0.010198876253436732,
 0.028074375404522425,
 -0.04762251055421213,
 0.036200668457086416,
 -0.013949772240068747,
 -0.010974219341779954,
 0.013696688429233678,
 -0.004664469733273548,
 0.017728418818920972,
 0.05260615665140679,
 -0.02702550980964393,
 0.012902993800090978,
 -0.007905495026198925,
 -0.005979858325965658,
 -0.021245499307169194,
 0.036513020270016065,
 0.014055852144936612,
 0.0034755904877533947,
 -0.04276528812459579,
 0.040107822431233946,
 -0.028040864401863576,
 -0.04570590602537968,
 0.03644872458936753,
 -0.09754805088605943,
 0.02342998622624772,
 0.01687237857668066,
 -0.0017773016760994976,
 -0.05383954867348488,
 -0.016137912537019468,
 -0.033484474543069825,
 0.030349751236518997,
 0.0047825509501797404,
 0.03634436684433154,
 0.010199668618318582,
 0.0124442164184511,
 -0.006708258593116529,
 0.023987050953715214,
 -0.022479772115469757,
 -0.024682877210243127,
 -0.007251618526865234,
 0.02181648182782523,
 0.04659407954241335,
 0.0001805884114358301,
 0.04534335453854479,
 0.0060732386301071495,
 0.017792942407288546,
 0.015230582776442996,
 -0.0057453227762770355,
 0.02461857638881898,
 0.0017723925781031246,
 -0.0127099964028288,
 -0.013597633394247174,
 -0.004176114213681425,
 -0.053561888528014245,
 -0.05277416062577162,
 -0.04215763645145987,
 0.016899345371978385,
 -0.029609787994130783,
 0.0065424303663522195,
 0.05762815636189202,
 -0.04244603910437929,
 -0.023829013229680906,
 0.047003855907662796,
 0.022536896414131823,
 0.0019692789721199692,
 0.006460110612311045,
 0.040926040273664165,
 -0.023494855960173543,
 -0.03370136043918995,
 0.04189386839529968,
 0.04390816993755966,
 0.0003727902668168271,
 0.009586569779338314,
 -0.015024773538186792,
 -0.014468541616369339,
 0.009868214025912543,
 -0.025675717775645767,
 0.013338398645385724,
 0.03137162090503793,
 0.025900355961397135,
 0.03179632436908884,
 0.011437125108959086,
 0.026395807636292516,
 -0.009620042397539217,
 0.01625517705603922,
 0.02087948122397621,
 0.007188852055603733,
 -0.0037466397671390684,
 0.017897128793137283,
 -0.01868444714692237,
 -0.0009858878377391096,
 0.0019043735954831999,
 -0.0013733022403143301,
 -0.00394521010788903,
 -0.007920205355628505,
 0.038025486150859614,
 0.0006731850469221341,
 -0.004564621819327634,
 -0.009664831233747817,
 0.009345932643069236,
 -0.034160604774615085,
 -0.020339065755142043,
 0.014850855958269914,
 0.005879657583453194,
 0.006302263782411334,
 0.024263485880997006,
 0.006850871248551233,
 0.007791808487008977,
 0.006755392137084288,
 -0.033068354460708334,
 0.007368802849785354,
 0.011210921214313805,
 0.03983709205129574,
 0.002245477766441729,
 -0.025225504926184705,
 -0.005576846021914571,
 -0.03677270826392779,
 -0.02949145762096633,
 0.023073207830431323,
 -0.00045811202818761814,
 0.028836675316968825,
 -0.05260108099228041,
 -0.042275911989684396,
 -0.0482360878280432,
 -0.01499402141844269,
 0.008252460366798196,
 0.0021880316552260054,
 0.0008794259732428602,
 -0.02602555184039881,
 0.005053773130985351,
 -0.018158437844960414,
 -0.07634019233796184,
 -0.0011937503017769567,
 -0.0008397537510063945,
 0.029980316251132223,
 0.030420395775055183,
 -0.020553835365299613,
 -0.0015808310680145992,
 0.003936707093658438,
 0.028153296591802844,
 -0.013308013234302337,
 -0.025716901385913787,
 0.006338870388787876,
 0.042414707790582276,
 -0.1320805599319496,
 0.03535943707580835,
 0.003965045619250108,
 0.048514700730594953,
 0.04588095114874867,
 -0.03479235469025416,
 0.00619735888749045,
 -0.03726130471453719,
 -0.0035643979006238996,
 0.022066128173364043,
 -0.023262883601207825,
 -0.0481630751055392,
 0.039406982204887066,
 -0.008312007684367993,
 0.008749144285609101,
 0.05357062613297218,
 -0.04852746870363704,
 0.02523294619889109,
 -0.011478207274588256,
 -0.034148907796493315,
 -0.012578549169317011,
 0.02403151523562316,
 -0.01144993129509993,
 0.040178427557157066,
 0.020292286410614334,
 -0.0025962589334227095,
 -0.03295738053745257,
 0.12059084074716178,
 0.0031345865619194072,
 3.84194015097371e-05,
 -0.010820671742529188,
 -0.003779350351034266,
 -0.006299904337762073,
 -0.03592398677257498,
 0.017993024821506814,
 0.04406323629328704,
 -0.03251543662557232,
 0.01579312414353504,
 0.06566157444855772,
 0.0040757931770195105,
 -0.009298663382625177,
 -0.06574930349806285,
 -0.006629410062131504,
 0.0060691661076629376,
 -0.0680905378064957,
 0.014605565563271031,
 -0.009943120952872418,
 -0.009693634485455313,
 -0.035651902655057494,
 -0.0032587193285233762,
 -0.04074988302916991,
 0.03098425660788906,
 0.028119653642569808,
 -0.020235790143373542,
 0.031823231188671024,
 0.023874980331661046,
 -0.02614902127558893,
 -0.05383817094561938,
 -0.010486291877437583,
 0.01875348433628214,
 0.023518088838781058,
 0.018445208301621264,
 -0.014706024886797057,
 0.01695967580103392,
 0.022895138217407345,
 0.030170372439304417,
 -0.02825415175505142,
 -0.014504153482663889,
 0.008026595591984485,
 0.010967866199912614,
 0.005072338185332148,
 -0.0011964445822781075,
 0.01001336314003694,
 -0.05021235105791715,
 -0.02108137490480372,
 0.012440988868159222,
 0.01929412085846786,
 -0.002543619104691008,
 -0.026219528726775316,
 0.05924180127484805,
 0.036444533143647366,
 -0.02937000508341015,
 -0.020126429566865753,
 0.04312868783940758,
 -0.026880978616748763,
 0.04288995021972918,
 0.014220613146682725,
 -0.02187403795163917,
 0.010757531365521105,
 -0.00918675846490508,
 0.046265321800896264,
 0.016250212780384556,
 0.01616717040465074,
 0.016484292857353464,
 -0.01597031811111216,
 0.055342008891384825,
 0.023330262033635002,
 0.03041746381936131,
 -0.0181985170452666,
 -0.018529834893041212,
 -0.038481337574377175,
 0.044318318152245455,
 -0.04222884304813024,
 0.007628833904789961,
 0.005608044360982277,
 0.0004106786913217638,
 -0.010367041648155963,
 0.0212449441034025,
 -0.010901412250300654,
 0.0005288105105959519,
 0.026530823253519624,
 -0.014552448499202834,
 -0.019248744945683738,
 -0.0017744565995135655,
 -0.02868390346075875,
 0.04565460108471667,
 -0.028834620720313682,
 0.011709824063240427,
 -0.020603555233480553,
 0.003349724594329566,
 -0.036119432207186226,
 -0.05743863995515966,
 -0.0279110272592752,
 -0.03933749776804857,
 0.016876912740775327,
 0.004875882588312053,
 -0.023835574572960753,
 0.014254227821649859,
 0.01121624602969845,
 0.007108964402507216,
 0.0040502562027802105,
 0.028901063531578473,
 4.036209204764479e-05,
 0.0410625004488398,
 -0.009159908193854685,
 0.0041942808579178625,
 -0.013999886234380367,
 -0.03450155814948883,
 0.029662491225761766,
 -0.012909498594839032,
 -0.01811911262507813,
 -0.030304676915904435,
 0.038786459743196694,
 0.003023777486201781,
 0.0035022063394356284,
 -0.009495070827713654,
 0.007954063360641538,
 0.039008388740197616,
 0.03977821646173997,
 -0.06118862328276038,
 -0.03652996769363521,
 -0.02199885084285734,
 0.03644525799300944,
 -0.019248906023319756,
 -0.029075330684237347,
 -0.05080399435578007,
 0.025361550412127194,
 0.0021205031121507944,
 -0.0033524671981215223,
 -0.01196543113810777,
 0.0032499335716338193,
 -0.008714649681215431,
 0.009456988647375692,
 -0.047333828585817486,
 0.03536397809427051,
 0.04428043063594421,
 0.02335784829239464,
 0.047486595301251946,
 -0.0158096654458804,
 0.03079282954621885,
 -0.045961669893903365,
 0.01711543444787779,
 -0.041937957400587554,
 -0.004827928062478174,
 -0.015873495029539605,
 -0.00622196572406135,
 -0.01716860549008997,
 0.001097516267410577,
 0.06028174076966262,
 -0.018705152477517934,
 -0.032216042994382604,
 -0.027971174334000377,
 0.006028242620641163,
 -0.009629651192605143,
 -0.04224762401505297,
 -0.0487384547029401,
 -0.01670263359297335,
 0.010088013028215936,
 0.0034966964561287525,
 -0.057921936266107386,
 0.015705986283225924,
 -0.07620198258548437,
 0.005216957799567937,
 -0.018347772610954282,
 -0.016669501294118327,
 -0.00807356411705492,
 0.038773597522601615,
 0.04012287976301771,
 0.005655070634098815,
 0.012437049320444317,
 -0.014640402886039202,
 -0.047478339215610184,
 0.0016475415594657914,
 -0.018039514569008066,
 0.0002353191923878411,
 -0.03312965649635558,
 0.02387422121046152,
 0.06774003458411643,
 -0.0063316971218503534,
 0.032033535178408824,
 0.03543939841335539,
 0.01891638694764251,
 -0.04297450226990268,
 -0.000352909533766234,
 0.02675934786563785,
 0.04149816061932356,
 -0.04852542267494126,
 0.03396663474260607,
 -0.012915600695497048,
 -0.07508617552410618,
 0.008149786911213697,
 -0.011891754227393986,
 0.019963557800159085,
 -0.008080973688311663,
 0.007016205960856259,
 0.0027277198756694774,
 -0.008246877827195924,
 -0.023909862207817902,
 -0.04045969652711121,
 -0.019211162448735802,
 0.027329552415583765,
 0.009124996672558434,
 0.00258902808979827,
 -0.03103359434508243,
 -0.006871520544692565,
 0.00600435909119965,
 0.02188853151169688,
 0.03307027539719742,
 -0.024371680358235552,
 0.045771978700800006,
 -0.016167453147309708,
 0.013239628409368431,
 0.023625728112252914,
 0.051552599241981356,
 -0.01823483576820856,
 -0.014327855723636089,
 -0.01836380154932976,
 0.0028230211163000553,
 0.003130349191937059,
 -0.0017102344319563667,
 0.01847890522899828,
 -0.008693166893987308,
 0.03555964458223331,
 -0.04971008014416511,
 0.03851257292702933,
 0.029325463689867947,
 0.011476791847701558,
 -0.054184827154244844,
 0.0008804124024042719,
 0.05702560605176057,
 0.006525130285525711,
 0.030228189029082978,
 0.0060183930659171506,
 -0.009210318810919436,
 -0.005280470540089915,
 -0.02801574485860442,
 0.04825676402757693,
 -0.01821628013861706,
 0.020988465667067982,
 -0.22506127158468994,
 0.02024768846854033,
 -0.04107086620436141,
 -0.021060768962536763,
 -0.0017838390290931313,
 -0.042610646739652806,
 -0.0009941199330946583,
 0.007073107492574899,
 -0.012055949915181354,
 0.0161774965092745,
 0.03403766998008919,
 -0.023008117043153944,
 0.014392595224579599,
 -0.031060249266659356,
 0.0003820146860898287,
 -0.010036363655586546,
 -0.011485230430877746,
 0.0611117069979708,
 0.006208818019060313,
 0.006266012917707527,
 -0.0481278899236209,
 0.019040594940929682,
 0.021288827477665664,
 -0.016584562828977578,
 -0.007005943259131784,
 -0.012415484623524688,
 0.0312953746346705,
 0.048461433727237914,
 0.005710806409266585,
 0.007378434949700745,
 -0.0009374109062869767,
 -0.002618295039466467,
 0.03835042943686848,
 -0.008733676548571871,
 0.02249649163136986,
 -0.03290823643614079,
 -0.026118968301328812,
 -0.014533274262945359,
 -0.005526513201920832,
 0.046032134505292935,
 -0.016585627826326346,
 0.04632211366273506,
 0.010054299821716132,
 -0.057724198045570704,
 -0.018602725950522266,
 0.01646593514762324,
 0.025708881775950432,
 -0.02107894760191631,
 -0.008502950827693404,
 -0.024543586181294104,
 -0.023603012738390893,
 0.005026434486251292,
 0.02317803338604851,
 0.0023258172937150284,
 -0.04407245713115302,
 -0.027390184436808865,
 -0.05698187175999031,
 0.03275204425055318,
 -0.04186415813941407,
 -0.0024720684187726364,
 0.008207658507291363,
 0.036370000465152444,
 0.03585563330637234,
 0.04252694805823182,
 -0.00675068095894919,
 0.030302385843570884,
 -0.049766231122643584,
 -0.006594084879757226,
 -0.02660465850012243,
 -0.06279288628021441,
 0.013252535697429757,
 -0.00041016192342077033,
 -0.06786219654870783,
 0.02402058594666028,
 0.02791438247216158,
 0.019494950398742543,
 -0.06562008667573233,
 0.05898004154836246,
 -0.016788475121030908,
 -0.01391824043602265,
 -0.02692524583559137,
 0.013727243485912442,
 -0.12056817849464779,
 -0.017778094133713226,
 -0.025606811676064246,
 0.0252675007790003,
 0.0267456922520058,
 0.04173733520492944,
 -0.03702469366237258,
 -0.018119093775567533,
 0.02358645087294306,
 0.016266415648335093,
 0.028586310976435433,
 0.05023764710113918,
 0.018771081211220966,
 -0.010287930937614442,
 0.02434026936241647,
 -0.02588367671490604,
 0.024591546190621972,
 0.0014934931629902851,
 -0.006510816995332991,
 0.025969849822990932,
 -0.01188140858782288,
 -0.010624123954266351,
 -0.06464859489467338,
 0.04060141742933546,
 0.002553292159452152,
 0.05848912832154143,
 -0.024955466837363,
 0.015519595468069029,
 -0.004186027685382283,
 0.008834337219142917,
 0.004402442515096651,
 -0.21538960483296266,
 -0.019110650003861727,
 -0.0460081476462615,
 -0.009321180665266736,
 0.012238312075845971,
 0.004621734122846592,
 -0.039363258194668044,
 0.034385842717521826,
 0.004871276110640366,
 0.0018893613311656823,
 -0.00212265538354267,
 -0.005338294326954342,
 -0.009602281703217377,
 -0.007254452807822368,
 0.037545335994589826,
 0.14474540901515004,
 -0.005295055091876054,
 0.01013472794168924,
 -0.00847021950933655,
 -0.020941381303186967,
 -0.03226642944980195,
 0.02392891906303211,
 -0.0354694205429618,
 -0.02177762784570789,
 0.015291171957871282,
 0.025663704639823523,
 0.006409719872912016,
 -0.004717815733215912,
 -0.016760801469085772,
 0.010723909836186481,
 0.027216626711185212,
 0.055033020859300924,
 -0.018168513765170785,
 0.024449073021565695,
 0.026563074766152175,
 0.014009211601350578,
 -0.04175030709540436,
 0.0013218505990511098,
 0.057234431211712386,
 0.035488256344824456,
 0.029060684614502983,
 0.023514053329921295,
 -0.004694952647734479,
 0.0038061075740459817,
 -0.013930177317006569,
 0.019214070414143455,
 0.0006742837334871141,
 0.021409248432914585,
 -0.002466146587979609,
 0.01121454717471604,
 -0.05017856245337495,
 -0.06672067018691512,
 -0.004626367846629053,
 0.031258739754028056,
 0.0419833504492904,
 0.011638042556496827,
 -0.010329300472600632,
 -0.017316862031715976,
 0.05093201166379984,
 -0.010281871676753238,
 -0.012182087926994536,
 -0.01407244913901783,
 -0.027051412464388823,
 0.026975728252155582,
 -0.07832138557165301,
 0.00962756917848004,
 -0.009513800386880213,
 0.018694728698157442,
 -0.0156980266489781,
 0.008461860608182435,
 0.010948843787895044,
 0.003851473719356431,
 -0.009364804259002027,
 0.038313929929983975,
 -0.008659706270929513,
 -0.018795825477860042,
 0.026068095185817673,
 -0.002596061184920622,
 -0.03122941676990563,
 0.016734893673565263,
 -0.03842255451878252,
 -0.02171641320324614,
 -0.021506613866314788,
 0.020931876009070143,
 0.04505526033216242,
 -0.03946997041493686,
 -0.010828916175746217,
 -0.004511857583825988,
 0.019987854819319438,
 -0.0344826400952163,
 0.023872427079771004,
 -0.029151458716765565,
 0.004075034227179175,
 -0.07485825580991896,
 -0.01765548663523498,
 -0.034121687389598455,
 -0.00870188136545497,
 0.029023525374747554,
 -0.003570938680801279,
 0.0053036790856928456,
 0.026190190320326035,
 -0.030209788479555945,
 -0.026609370877771838,
 -0.06089753029060112,
 -0.011902949465815481,
 0.013179772302543207,
 -0.006652800762550482,
 0.03541426344776938,
 0.030844639996484256,
 -0.01196315206091733]

In [9]:
embeddings = np.array(dataset.embedding.tolist())

query = "I love soccer"
xq = get_embedding(query)

In [10]:
xq

[-0.0034452482279799922,
 0.011365492491404058,
 0.018777735968417898,
 -0.12166101543439739,
 -0.05937419152954507,
 0.048525747454869,
 0.01319895550712965,
 -0.002090941373957385,
 0.026493277680751787,
 0.017328222982419286,
 0.0022860522422352677,
 -0.04302188773968902,
 -0.05096342505701343,
 0.04438796350469139,
 0.19840253859823045,
 -0.026371519207629424,
 -0.018915473225971202,
 -0.009634750523645765,
 -0.0008746975980712101,
 0.011211854510601187,
 -0.044567432948600445,
 0.003950913966877795,
 0.0021153670570059424,
 -0.01614206975557438,
 -0.021038604994748834,
 0.009978363965181392,
 0.05499159922966565,
 0.03329673048913602,
 0.03759898595450553,
 0.009156405689134414,
 -0.023497997181173045,
 0.03698190383082819,
 0.021514167287540617,
 0.033769070212722796,
 0.015390953189512406,
 0.02577746682943979,
 0.051139178109896176,
 0.05860575216914675,
 0.033630143370644634,
 0.051936873443487935,
 -0.04024948379181023,
 -0.007232918785686769,
 0.018269927619789583,
 -0.01644931347451825,
 0.03486913044142252,
 0.019800983994645003,
 0.026959345358113333,
 -0.0073883715192583806,
 -0.02032649186765891,
 0.01006495112454432,
 -0.00957885871778154,
 -0.04214080100362052,
 0.0010873981281068119,
 -0.2800171497981281,
 0.01545423365589196,
 -0.0020498589620874673,
 -0.026345068346018855,
 -0.0034012240974597946,
 0.0009826910509569465,
 0.043726946511757764,
 -0.021909189107958044,
 0.07380375339114094,
 -0.04303343230962144,
 -0.054620279159688645,
 -0.0297086279234654,
 -0.02821257859449209,
 0.02940001304290086,
 -0.028558221626743457,
 -0.019897976709485163,
 0.036924808864581465,
 -0.0007207913243819174,
 -0.02250474840634465,
 0.016511731873938278,
 0.02714801244556696,
 -0.01908728928014114,
 -0.028926193550832372,
 0.027769099447245274,
 0.04519920415023385,
 0.001143048521282724,
 0.04434691859612818,
 0.015195766296431795,
 0.023803723798026727,
 -0.006864767660277132,
 -0.03251444545093693,
 -0.018106666052908983,
 -0.021954966899887643,
 -0.06608185478347163,
 0.01611044140126003,
 -0.024500088930265423,
 0.008436487631794571,
 0.020293607746513752,
 -0.00879711603509478,
 -0.01983300604883063,
 0.0408206642438571,
 -0.032348112346267464,
 -0.006132384080762864,
 0.005376723505453787,
 -0.01241756545734484,
 0.01995111601021483,
 -0.011203457842656804,
 -0.040743061247677514,
 -0.03284984549860619,
 -0.05831690373729202,
 0.005258292475036629,
 0.007641979230781535,
 0.009641833218269747,
 0.030896803953097227,
 -0.03730274037722446,
 -0.02187596219640772,
 0.05234273558622321,
 -0.013396534126928294,
 0.04257668276154094,
 -0.029988460288871352,
 0.019347275438673702,
 0.04914578741852756,
 -0.2598766862105959,
 0.010332136051283605,
 -0.024805374331746118,
 -0.017971338510085068,
 0.026565333242107168,
 0.04851852170464523,
 0.001397261139082244,
 -0.031032800106909435,
 0.05662476132674127,
 0.013527391818627409,
 0.002294076422585917,
 0.024171415720052016,
 -0.02840796573147275,
 -0.014126348475386016,
 0.008402409683669041,
 0.026991693232882093,
 -0.00971390795552403,
 0.015614421988001484,
 0.009315291078307865,
 -0.02650836724650794,
 0.03140528091271384,
 0.002690320070190074,
 -0.01916450875834267,
 -0.021284176986442353,
 -0.01686483314297533,
 0.03796336536726901,
 0.017313258993346212,
 -0.02353525612243959,
 0.021109734003820945,
 -0.004844348963650439,
 -0.010330470293552357,
 -0.011179630006438642,
 0.060923804404799,
 -0.004301179408954084,
 -0.009006610185135598,
 0.005210700948527612,
 0.0212583149776565,
 -0.035561621363289955,
 -0.009898877318755588,
 0.034709622599176725,
 -0.11551054780217623,
 0.019727392664395185,
 0.008747711622497446,
 0.019709170469490823,
 -0.019541515415684593,
 -0.023421955408620947,
 0.020686829068812945,
 0.015884076702640176,
 -0.012269408729060228,
 0.009168669270426586,
 -0.00028758760801694843,
 -0.036092137030787265,
 -0.03248112350838319,
 0.041239616907312454,
 0.04685269439712874,
 -0.04487081773001289,
 0.03825515466928291,
 0.0043901224887105406,
 0.021759951402009613,
 -0.004908489460610874,
 -0.014250694846369165,
 0.002436034414276503,
 0.011076047400606479,
 -0.021983457534107173,
 0.001492335992514965,
 0.023720121969756716,
 -0.020216810816880964,
 0.00947679372313423,
 -0.01794776233632773,
 -0.00015693014324805887,
 -0.035130990068308075,
 -0.06593998198028768,
 -0.03325707201503331,
 0.04599904107536681,
 0.012851135925503692,
 0.02907330493807945,
 -0.01436420768296328,
 -0.017904472320308895,
 -0.01893862515417759,
 0.03775061979932572,
 0.017038062783321022,
 0.031036569104384067,
 0.012889662512476472,
 0.03270906046101486,
 -0.023987086119111288,
 0.01767024804861216,
 0.0646750242938629,
 0.03094187240646564,
 0.02905011907022898,
 0.026294157182922773,
 0.0014939388940253824,
 -0.050141561302875205,
 -0.053924058270937276,
 -0.035618580570960366,
 0.03784175622858058,
 0.020530263793708526,
 0.005195226676905857,
 0.04203566616816654,
 0.0067650341494796176,
 0.02935774461016871,
 -0.01955692571107727,
 0.009345590356160201,
 -0.011361625068961607,
 -0.027119642297083902,
 -0.008313050843272655,
 0.03303757415490111,
 -0.021017100836262334,
 0.010434142839441322,
 0.006270035131620216,
 -0.007372414625897867,
 -0.004871863154309906,
 -0.017519665484267224,
 0.005670263244610906,
 -0.015916113181174536,
 0.06214908834428123,
 -0.024629298852244654,
 0.0015018935659849642,
 -0.012220382404097901,
 -0.0298982198662201,
 0.03124959637137319,
 -0.01051150791871594,
 0.012982589257956341,
 0.010458297684130155,
 0.03886760572852611,
 0.028624858723922116,
 -0.019076537200897886,
 -0.048131039576159274,
 0.025121065628100486,
 0.03553649923874496,
 -0.0025175616818023713,
 -0.02774048663030707,
 0.008233840804946069,
 0.003198066139571511,
 -0.017077242708442266,
 0.0048309528164354534,
 -0.029827929166356664,
 -0.006729786810917453,
 0.03560473998410621,
 -0.043772109996129585,
 -0.020774384865617803,
 0.0067654110492270806,
 -0.02138463154497826,
 0.011719160552497178,
 0.03165310140582739,
 -0.0016487368300438377,
 -0.050948742766986195,
 -0.012484102941668138,
 -0.032076834468150836,
 -0.062219733713425256,
 0.015294710540806323,
 -0.01909423672528348,
 0.026229210280019094,
 -0.005550558459351578,
 0.023343537860983535,
 0.0062646504373893505,
 -0.004177201113410937,
 0.051637035354881435,
 -0.01481357366147507,
 -0.023178224642618546,
 -0.015694378698497737,
 0.028903793385742265,
 -0.09923159437109705,
 0.026454141877167842,
 -0.014747167353876123,
 0.021251820626762577,
 0.03124188358725694,
 0.03512593815228738,
 0.007821920435743247,
 -0.008013541969213684,
 -0.03764947456903287,
 0.04127410128267579,
 0.0074536939643237606,
 -0.02396586875061723,
 0.030688224476464257,
 -0.009711579695940423,
 -0.0003602637727340797,
 0.041749186723468314,
 -0.01970869870843817,
 0.03866420374459692,
 0.02068777428790046,
 -0.02761016348800215,
 0.01997119300666794,
 -0.008839614748311984,
 -0.008146357978375979,
 0.03148192341696608,
 -0.01878016944089814,
 0.008450231999757776,
 -0.01892166381705065,
 0.06852594528136421,
 0.032089295408473315,
 -0.018789955937267434,
 -0.013844096213357443,
 -0.008737448274128888,
 0.023823474973896707,
 -0.00019922045008081602,
 0.043144723796510784,
 0.02017268079467125,
 -0.010213528365019032,
 0.04612104051996211,
 0.02747269944458365,
 -0.011717536031433485,
 0.05181806432543578,
 -0.010537620571773293,
 -0.0399028310551476,
 0.02293682383318196,
 0.034211789111942316,
 -0.025546480399787897,
 -0.0044589722809847306,
 0.01039371461421097,
 -0.003992846906228255,
 0.010996966163229161,
 -0.03581456334869456,
 -0.03718519041996752,
 0.016709469331271192,
 0.013380395826170195,
 0.039579496550947335,
 0.005523368731689478,
 0.026530341469064897,
 0.0032708850035221594,
 -0.014891692540244613,
 0.028768219780498802,
 0.0034928327968619744,
 0.028316372814005064,
 -0.017335341822764208,
 0.043165532192293736,
 -0.03145161022385967,
 0.0019662746127341577,
 -0.0745841038696277,
 -0.032588871696431015,
 0.014439378903644832,
 0.017935510124816326,
 -0.00033148512669492074,
 0.00830187248209981,
 0.05024762608457686,
 -0.07177300533353796,
 -0.004133734780941127,
 0.047973883751247934,
 -0.01423729038394138,
 0.01953894194217254,
 -0.0328734131874525,
 0.013849441707299402,
 0.008675964063412055,
 0.02520895742738169,
 0.024761298612966925,
 0.02629475961160512,
 0.004379439137246543,
 0.03972366367407082,
 0.007384277210295282,
 -0.0296607051460302,
 0.01400010487829902,
 0.011760302189046008,
 0.056812045373698807,
 0.009604672362574583,
 0.014871066570048575,
 -0.0019037559216658895,
 0.02052088117910374,
 0.0009987686506616167,
 0.0290993027054416,
 -0.00023787050947874432,
 -0.011215851243087566,
 -0.027397489193311413,
 -0.06199526539241814,
 0.0276345066977156,
 0.019777642004431786,
 -0.025837756364685154,
 0.010348731519047407,
 0.03094036039532206,
 -0.008999306204032238,
 0.0069207040967733165,
 0.0011342404200030312,
 -0.004087129031394294,
 0.021529932252213883,
 -0.007894026906564742,
 -0.026137639423320057,
 -0.0047363319736215366,
 0.03268250608348987,
 0.03916298754186545,
 -0.03307186337731102,
 0.02815158396314105,
 -0.03250417870860396,
 0.02106223038099008,
 0.01736539198362903,
 -0.04592496949915332,
 -0.043946921223889227,
 -0.010902180713141477,
 0.028684633225068625,
 0.012605587182466365,
 -0.0031062330991219896,
 -0.020539687135886206,
 0.009933351512225703,
 0.011755435753180183,
 -0.0024195010560613597,
 -0.044839482953619794,
 0.009729217110777356,
 0.01121201742089275,
 -0.011507748812566072,
 -0.009132143425472083,
 0.0021671759236878336,
 -0.02613011161026402,
 0.013689767560797626,
 -0.02309198570400384,
 -0.04038935076202929,
 -0.04063021193112508,
 0.037481505573518946,
 0.02344281980481662,
 0.012204951744918785,
 0.01663690806921908,
 0.04024739141275295,
 0.04183806446940992,
 -0.01609014888806704,
 -0.06540306868988206,
 -0.025584654014462284,
 -0.028380683348582323,
 0.04576179956931172,
 -0.004685529926481157,
 0.03100719773640077,
 -0.015376939510473461,
 -0.009948330774138611,
 -0.00016907816005215276,
 -0.019267278000604553,
 0.009589132248043319,
 -0.004689711799725971,
 0.028892920820762544,
 0.06953173475467866,
 -0.02063953672026646,
 0.017868985028463114,
 0.051429893222175074,
 0.038926497798926644,
 0.046949266260382365,
 0.01389226335622999,
 0.02685126286457136,
 -0.007861921700251125,
 0.05763236657101378,
 -0.0040979948084452,
 0.039551258767076165,
 0.03219862009298846,
 0.017844667273482717,
 -0.009114152020147438,
 0.032177154965092644,
 0.027633963663410383,
 -0.009760042113716427,
 -0.052590238743664655,
 0.004106602580975735,
 0.010110101202756735,
 -0.03459504745172303,
 -0.021276118017956525,
 -0.017985270733978233,
 -0.02472712478534688,
 -0.03362432781263222,
 -0.03138262110934655,
 -0.022238760021757262,
 0.024783330532918806,
 -0.05135904251818439,
 -0.0037180119837142574,
 0.01300372958345835,
 0.008986021887944482,
 0.019003673876013497,
 -0.025952082904245985,
 0.02153089613810564,
 -0.009281025613648816,
 0.04498459359884859,
 -0.011924590430159905,
 -0.004279509625004491,
 0.010242084333053408,
 0.0013480823232990841,
 0.013499949919409823,
 -0.00017229446739282933,
 0.015692873475282972,
 -0.0059294570821525165,
 0.02837933764169471,
 -0.0013834457354439883,
 0.0035785514407329975,
 -0.017566996863404398,
 -0.050225059615230785,
 -7.078818037836921e-05,
 0.03380418416848375,
 0.05923078804841329,
 -0.05059893024946009,
 -0.009436280648793687,
 -0.019711721033743128,
 -0.03127916968023874,
 -0.022560543484223258,
 -0.010576403742455286,
 0.007764098482320424,
 -0.023972565042393406,
 -0.009134104118710348,
 0.029178225953775744,
 -0.011857181884871398,
 -0.001356113121880328,
 -0.014962366758086102,
 0.046576150783233745,
 0.028795780468470655,
 -0.056407135237979855,
 0.013758203459112313,
 0.015306248322809931,
 -0.011400150977141506,
 -0.014680772925152607,
 0.03600805156258917,
 -0.0012056525026765547,
 -0.008583473442358562,
 0.02436099238996688,
 -0.026805463011873115,
 0.04192162047916043,
 0.01218601732658349,
 0.019457857587001862,
 0.009690733457454331,
 0.007517826315769618,
 -0.009578805262842119,
 -0.004069184123382034,
 -0.025047058537210738,
 -0.0007412354120253528,
 0.01240502560734989,
 0.018102939479989446,
 0.00518436005136385,
 -0.00929806348467315,
 0.012080329274931075,
 0.06860204984225786,
 0.01189201244460431,
 -0.04503988297603047,
 -0.03814447070202252,
 0.05559354427208515,
 0.0017062993148876993,
 0.02397964315516544,
 0.029732675858275392,
 0.02372604613463017,
 0.010970403809887804,
 -0.012136522804231135,
 -0.027776754533966594,
 -0.05482911827459879,
 0.08070853470389604,
 -0.21595322067472755,
 0.07332225675158248,
 -0.021295037672546646,
 -0.018812651377261,
 0.0010284102460910499,
 -0.0263466957519523,
 -0.031607469554367315,
 -0.029567272699853604,
 -0.06178123690592878,
 0.022446295854334896,
 0.053411130127000106,
 0.006168234357102037,
 0.029234582732763807,
 0.04948725078361098,
 -0.01358393526565789,
 -0.019716798404496885,
 0.006573386652181462,
 0.010028212308323238,
 -0.004885236052868699,
 -0.024662184670372015,
 -0.010925505733532652,
 0.0030150666332821197,
 0.01730937799504613,
 -0.012710938043754883,
 0.01743520074054658,
 0.012220618793718888,
 0.05648549508822234,
 0.034965045572563275,
 -0.03989879223750257,
 -0.03279742062738432,
 -0.014107170879500917,
 0.0042049528815789345,
 -0.016720711838371344,
 0.018045661239664723,
 -0.05766256436933034,
 -0.001680410324084808,
 -0.030859348161895048,
 -0.013699075508185447,
 -0.028295387932072924,
 0.02718152105616312,
 -0.03405903016792101,
 -0.02615632150040165,
 -0.002275109931286971,
 -0.018242049596145622,
 0.009071015411319825,
 -0.013202429908493702,
 0.04728543843495435,
 -0.020282843788395073,
 -0.030505814162396023,
 -0.017579366166687864,
 -0.020157430015605736,
 0.030584857896466637,
 0.018542717509049785,
 0.016900054857106214,
 -0.045466999820868284,
 -0.008405090745852817,
 -0.012415006917276176,
 0.01610923060445762,
 -0.05043479303976234,
 -0.01094989527086027,
 -0.006106751673669187,
 0.035337244679321846,
 0.009511767847561584,
 0.04173830737055977,
 -0.03719269956621931,
 -0.010263334113907561,
 0.019463943813675774,
 0.01571439290660931,
 0.0046342683365599895,
 -0.03215391309682945,
 0.013993361071021134,
 0.026496237217715206,
 -0.02995035625046732,
 0.04721908982475033,
 0.02454617217899171,
 0.03061382029173882,
 -0.028286953930520057,
 0.04100854223458597,
 -0.014354736825283897,
 -0.00036610040726545965,
 -0.028726916930640608,
 0.03533182621514513,
 -0.1333598410491465,
 -0.048573305381130374,
 0.003682218895675352,
 0.02339079202743044,
 0.07326499548107979,
 0.010074472552293377,
 -0.05149419527184131,
 0.019456486425381194,
 0.007868049502989033,
 0.017218767630274443,
 0.0377207020030728,
 -0.009584534444460356,
 0.016073129853545167,
 0.0034679019222113466,
 0.005862473291509621,
 -0.021930228293320704,
 -0.010729890352445582,
 -0.005436813305893762,
 0.008706431681899007,
 -0.03160014368219353,
 0.02006649892119753,
 -0.033587992029684544,
 -0.026226411956365034,
 -0.007363489178298781,
 0.014476753239701235,
 0.028316113175727884,
 -0.02482482174780162,
 0.015148379765372996,
 0.016540030749168776,
 -0.03169844646729502,
 0.03792345064885353,
 -0.24470955139790654,
 -0.015896388308528714,
 -0.003926902347486964,
 0.007641007538771643,
 0.049585952359530366,
 0.0003977244003355453,
 -0.02787340106443718,
 0.029177309583385696,
 -0.003083127159133324,
 -0.0013686157061460831,
 -0.025232984998405237,
 -0.04239696725521233,
 -0.058534012246481276,
 -0.009672569469039561,
 0.05658497897293768,
 0.20111315542406902,
 -0.036674839991997915,
 0.0034503849931108825,
 -0.03197929023409444,
 0.00968366501748086,
 -0.040219954604481974,
 -0.048358942589146865,
 -0.02286949097329974,
 -0.030824850210674073,
 0.03448613004293679,
 0.04369680131988953,
 0.06153910130319796,
 -0.02190717139611773,
 -0.027951407942381275,
 0.02150322344930834,
 -0.0303682466030631,
 0.03392613440059514,
 0.001856258577669183,
 -0.01880135965767694,
 0.01581441643166545,
 0.026480752255105565,
 -0.018372549224599737,
 -0.021711134314953015,
 0.020240066261001784,
 0.05084050075711707,
 0.018452784240177413,
 0.0323739675671245,
 -0.017909376598877865,
 0.06042234107263068,
 -0.02622293144586505,
 -0.014354080093171026,
 -0.015220990239909018,
 0.027528275611757972,
 0.02695547623868868,
 -0.048358817012463785,
 -0.008470890552012127,
 -0.12293819818061834,
 -0.0013167087878324564,
 0.0720563589370168,
 0.027263349538030158,
 0.02814126291737756,
 0.0003682676232379275,
 0.04468312810430864,
 -0.030641542193020038,
 0.009590805472496263,
 -0.010014237320478537,
 -0.0006147979177517529,
 -0.007249190129849646,
 0.01798989161651917,
 -0.01647305764951377,
 -0.015331791298941468,
 -0.016758600360035496,
 0.009339910047629435,
 0.00767994411664486,
 -0.002186435314115155,
 -0.028103722277065188,
 0.0504684849244365,
 0.03777436397432123,
 -0.005274669032096142,
 -0.05030626530462903,
 -0.02201401509265093,
 0.0051296196479249006,
 0.009491883288890385,
 0.03738868573791791,
 0.02139529368416471,
 -0.022682683778341473,
 0.0331828120737952,
 0.0046665011559353315,
 0.036154361974236056,
 0.01027899793844148,
 0.022358285266299426,
 0.004937448292220433,
 -0.025607693941843226,
 -0.01988893518830334,
 0.019229396266869217,
 0.022290952406417208,
 0.001884826254880766,
 0.004909912210490537,
 -0.04645302793641953,
 -0.023789974848211572,
 -0.024213597606691773,
 0.031780919802399506,
 -0.019836284618448365,
 0.022875671382485963,
 -0.012594524046385157,
 0.017889964819448642,
 -0.037249570530815124,
 -0.014145755163868626,
 -0.047132301063901594,
 -0.014324739270867394,
 -0.010703889021420799,
 0.016741034897244003,
 0.0376632116399726,
 0.026144257653914864,
 0.03969879439987419]

In [14]:
def search(query, k=5):
    xq = np.array(get_embedding(query))
    scores = embeddings @ xq
    top_idx = np.argsort(scores)[::-1][:k]
    return dataset.iloc[top_idx].assign(score=scores[top_idx])[["id", "sentence", "score"]]


search("A man is drawing on a digital dry erase board",5)

    id                                           sentence     score
1    2      A man is drawing on a digital dry erase board  1.000000
19  20                           A man is shaking a drink  0.773893
20  21                      A man is speaking on a podium  0.766929
16  17                         A man is playing the piano  0.764777
6    7  A man is opening a small package that contains...  0.758045

## Faiss

Check [Faiss Indexes](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes) for more information.

In [8]:
embeddings = np.array(dataset.embedding.tolist())

query = "I love soccer"
xq = get_embedding(query)

In [11]:
xq

[-0.0034452482279799922,
 0.011365492491404058,
 0.018777735968417898,
 -0.12166101543439739,
 -0.05937419152954507,
 0.048525747454869,
 0.01319895550712965,
 -0.002090941373957385,
 0.026493277680751787,
 0.017328222982419286,
 0.0022860522422352677,
 -0.04302188773968902,
 -0.05096342505701343,
 0.04438796350469139,
 0.19840253859823045,
 -0.026371519207629424,
 -0.018915473225971202,
 -0.009634750523645765,
 -0.0008746975980712101,
 0.011211854510601187,
 -0.044567432948600445,
 0.003950913966877795,
 0.0021153670570059424,
 -0.01614206975557438,
 -0.021038604994748834,
 0.009978363965181392,
 0.05499159922966565,
 0.03329673048913602,
 0.03759898595450553,
 0.009156405689134414,
 -0.023497997181173045,
 0.03698190383082819,
 0.021514167287540617,
 0.033769070212722796,
 0.015390953189512406,
 0.02577746682943979,
 0.051139178109896176,
 0.05860575216914675,
 0.033630143370644634,
 0.051936873443487935,
 -0.04024948379181023,
 -0.007232918785686769,
 0.018269927619789583,
 -0.01644931347451825,
 0.03486913044142252,
 0.019800983994645003,
 0.026959345358113333,
 -0.0073883715192583806,
 -0.02032649186765891,
 0.01006495112454432,
 -0.00957885871778154,
 -0.04214080100362052,
 0.0010873981281068119,
 -0.2800171497981281,
 0.01545423365589196,
 -0.0020498589620874673,
 -0.026345068346018855,
 -0.0034012240974597946,
 0.0009826910509569465,
 0.043726946511757764,
 -0.021909189107958044,
 0.07380375339114094,
 -0.04303343230962144,
 -0.054620279159688645,
 -0.0297086279234654,
 -0.02821257859449209,
 0.02940001304290086,
 -0.028558221626743457,
 -0.019897976709485163,
 0.036924808864581465,
 -0.0007207913243819174,
 -0.02250474840634465,
 0.016511731873938278,
 0.02714801244556696,
 -0.01908728928014114,
 -0.028926193550832372,
 0.027769099447245274,
 0.04519920415023385,
 0.001143048521282724,
 0.04434691859612818,
 0.015195766296431795,
 0.023803723798026727,
 -0.006864767660277132,
 -0.03251444545093693,
 -0.018106666052908983,
 -0.021954966899887643,
 -0.06608185478347163,
 0.01611044140126003,
 -0.024500088930265423,
 0.008436487631794571,
 0.020293607746513752,
 -0.00879711603509478,
 -0.01983300604883063,
 0.0408206642438571,
 -0.032348112346267464,
 -0.006132384080762864,
 0.005376723505453787,
 -0.01241756545734484,
 0.01995111601021483,
 -0.011203457842656804,
 -0.040743061247677514,
 -0.03284984549860619,
 -0.05831690373729202,
 0.005258292475036629,
 0.007641979230781535,
 0.009641833218269747,
 0.030896803953097227,
 -0.03730274037722446,
 -0.02187596219640772,
 0.05234273558622321,
 -0.013396534126928294,
 0.04257668276154094,
 -0.029988460288871352,
 0.019347275438673702,
 0.04914578741852756,
 -0.2598766862105959,
 0.010332136051283605,
 -0.024805374331746118,
 -0.017971338510085068,
 0.026565333242107168,
 0.04851852170464523,
 0.001397261139082244,
 -0.031032800106909435,
 0.05662476132674127,
 0.013527391818627409,
 0.002294076422585917,
 0.024171415720052016,
 -0.02840796573147275,
 -0.014126348475386016,
 0.008402409683669041,
 0.026991693232882093,
 -0.00971390795552403,
 0.015614421988001484,
 0.009315291078307865,
 -0.02650836724650794,
 0.03140528091271384,
 0.002690320070190074,
 -0.01916450875834267,
 -0.021284176986442353,
 -0.01686483314297533,
 0.03796336536726901,
 0.017313258993346212,
 -0.02353525612243959,
 0.021109734003820945,
 -0.004844348963650439,
 -0.010330470293552357,
 -0.011179630006438642,
 0.060923804404799,
 -0.004301179408954084,
 -0.009006610185135598,
 0.005210700948527612,
 0.0212583149776565,
 -0.035561621363289955,
 -0.009898877318755588,
 0.034709622599176725,
 -0.11551054780217623,
 0.019727392664395185,
 0.008747711622497446,
 0.019709170469490823,
 -0.019541515415684593,
 -0.023421955408620947,
 0.020686829068812945,
 0.015884076702640176,
 -0.012269408729060228,
 0.009168669270426586,
 -0.00028758760801694843,
 -0.036092137030787265,
 -0.03248112350838319,
 0.041239616907312454,
 0.04685269439712874,
 -0.04487081773001289,
 0.03825515466928291,
 0.0043901224887105406,
 0.021759951402009613,
 -0.004908489460610874,
 -0.014250694846369165,
 0.002436034414276503,
 0.011076047400606479,
 -0.021983457534107173,
 0.001492335992514965,
 0.023720121969756716,
 -0.020216810816880964,
 0.00947679372313423,
 -0.01794776233632773,
 -0.00015693014324805887,
 -0.035130990068308075,
 -0.06593998198028768,
 -0.03325707201503331,
 0.04599904107536681,
 0.012851135925503692,
 0.02907330493807945,
 -0.01436420768296328,
 -0.017904472320308895,
 -0.01893862515417759,
 0.03775061979932572,
 0.017038062783321022,
 0.031036569104384067,
 0.012889662512476472,
 0.03270906046101486,
 -0.023987086119111288,
 0.01767024804861216,
 0.0646750242938629,
 0.03094187240646564,
 0.02905011907022898,
 0.026294157182922773,
 0.0014939388940253824,
 -0.050141561302875205,
 -0.053924058270937276,
 -0.035618580570960366,
 0.03784175622858058,
 0.020530263793708526,
 0.005195226676905857,
 0.04203566616816654,
 0.0067650341494796176,
 0.02935774461016871,
 -0.01955692571107727,
 0.009345590356160201,
 -0.011361625068961607,
 -0.027119642297083902,
 -0.008313050843272655,
 0.03303757415490111,
 -0.021017100836262334,
 0.010434142839441322,
 0.006270035131620216,
 -0.007372414625897867,
 -0.004871863154309906,
 -0.017519665484267224,
 0.005670263244610906,
 -0.015916113181174536,
 0.06214908834428123,
 -0.024629298852244654,
 0.0015018935659849642,
 -0.012220382404097901,
 -0.0298982198662201,
 0.03124959637137319,
 -0.01051150791871594,
 0.012982589257956341,
 0.010458297684130155,
 0.03886760572852611,
 0.028624858723922116,
 -0.019076537200897886,
 -0.048131039576159274,
 0.025121065628100486,
 0.03553649923874496,
 -0.0025175616818023713,
 -0.02774048663030707,
 0.008233840804946069,
 0.003198066139571511,
 -0.017077242708442266,
 0.0048309528164354534,
 -0.029827929166356664,
 -0.006729786810917453,
 0.03560473998410621,
 -0.043772109996129585,
 -0.020774384865617803,
 0.0067654110492270806,
 -0.02138463154497826,
 0.011719160552497178,
 0.03165310140582739,
 -0.0016487368300438377,
 -0.050948742766986195,
 -0.012484102941668138,
 -0.032076834468150836,
 -0.062219733713425256,
 0.015294710540806323,
 -0.01909423672528348,
 0.026229210280019094,
 -0.005550558459351578,
 0.023343537860983535,
 0.0062646504373893505,
 -0.004177201113410937,
 0.051637035354881435,
 -0.01481357366147507,
 -0.023178224642618546,
 -0.015694378698497737,
 0.028903793385742265,
 -0.09923159437109705,
 0.026454141877167842,
 -0.014747167353876123,
 0.021251820626762577,
 0.03124188358725694,
 0.03512593815228738,
 0.007821920435743247,
 -0.008013541969213684,
 -0.03764947456903287,
 0.04127410128267579,
 0.0074536939643237606,
 -0.02396586875061723,
 0.030688224476464257,
 -0.009711579695940423,
 -0.0003602637727340797,
 0.041749186723468314,
 -0.01970869870843817,
 0.03866420374459692,
 0.02068777428790046,
 -0.02761016348800215,
 0.01997119300666794,
 -0.008839614748311984,
 -0.008146357978375979,
 0.03148192341696608,
 -0.01878016944089814,
 0.008450231999757776,
 -0.01892166381705065,
 0.06852594528136421,
 0.032089295408473315,
 -0.018789955937267434,
 -0.013844096213357443,
 -0.008737448274128888,
 0.023823474973896707,
 -0.00019922045008081602,
 0.043144723796510784,
 0.02017268079467125,
 -0.010213528365019032,
 0.04612104051996211,
 0.02747269944458365,
 -0.011717536031433485,
 0.05181806432543578,
 -0.010537620571773293,
 -0.0399028310551476,
 0.02293682383318196,
 0.034211789111942316,
 -0.025546480399787897,
 -0.0044589722809847306,
 0.01039371461421097,
 -0.003992846906228255,
 0.010996966163229161,
 -0.03581456334869456,
 -0.03718519041996752,
 0.016709469331271192,
 0.013380395826170195,
 0.039579496550947335,
 0.005523368731689478,
 0.026530341469064897,
 0.0032708850035221594,
 -0.014891692540244613,
 0.028768219780498802,
 0.0034928327968619744,
 0.028316372814005064,
 -0.017335341822764208,
 0.043165532192293736,
 -0.03145161022385967,
 0.0019662746127341577,
 -0.0745841038696277,
 -0.032588871696431015,
 0.014439378903644832,
 0.017935510124816326,
 -0.00033148512669492074,
 0.00830187248209981,
 0.05024762608457686,
 -0.07177300533353796,
 -0.004133734780941127,
 0.047973883751247934,
 -0.01423729038394138,
 0.01953894194217254,
 -0.0328734131874525,
 0.013849441707299402,
 0.008675964063412055,
 0.02520895742738169,
 0.024761298612966925,
 0.02629475961160512,
 0.004379439137246543,
 0.03972366367407082,
 0.007384277210295282,
 -0.0296607051460302,
 0.01400010487829902,
 0.011760302189046008,
 0.056812045373698807,
 0.009604672362574583,
 0.014871066570048575,
 -0.0019037559216658895,
 0.02052088117910374,
 0.0009987686506616167,
 0.0290993027054416,
 -0.00023787050947874432,
 -0.011215851243087566,
 -0.027397489193311413,
 -0.06199526539241814,
 0.0276345066977156,
 0.019777642004431786,
 -0.025837756364685154,
 0.010348731519047407,
 0.03094036039532206,
 -0.008999306204032238,
 0.0069207040967733165,
 0.0011342404200030312,
 -0.004087129031394294,
 0.021529932252213883,
 -0.007894026906564742,
 -0.026137639423320057,
 -0.0047363319736215366,
 0.03268250608348987,
 0.03916298754186545,
 -0.03307186337731102,
 0.02815158396314105,
 -0.03250417870860396,
 0.02106223038099008,
 0.01736539198362903,
 -0.04592496949915332,
 -0.043946921223889227,
 -0.010902180713141477,
 0.028684633225068625,
 0.012605587182466365,
 -0.0031062330991219896,
 -0.020539687135886206,
 0.009933351512225703,
 0.011755435753180183,
 -0.0024195010560613597,
 -0.044839482953619794,
 0.009729217110777356,
 0.01121201742089275,
 -0.011507748812566072,
 -0.009132143425472083,
 0.0021671759236878336,
 -0.02613011161026402,
 0.013689767560797626,
 -0.02309198570400384,
 -0.04038935076202929,
 -0.04063021193112508,
 0.037481505573518946,
 0.02344281980481662,
 0.012204951744918785,
 0.01663690806921908,
 0.04024739141275295,
 0.04183806446940992,
 -0.01609014888806704,
 -0.06540306868988206,
 -0.025584654014462284,
 -0.028380683348582323,
 0.04576179956931172,
 -0.004685529926481157,
 0.03100719773640077,
 -0.015376939510473461,
 -0.009948330774138611,
 -0.00016907816005215276,
 -0.019267278000604553,
 0.009589132248043319,
 -0.004689711799725971,
 0.028892920820762544,
 0.06953173475467866,
 -0.02063953672026646,
 0.017868985028463114,
 0.051429893222175074,
 0.038926497798926644,
 0.046949266260382365,
 0.01389226335622999,
 0.02685126286457136,
 -0.007861921700251125,
 0.05763236657101378,
 -0.0040979948084452,
 0.039551258767076165,
 0.03219862009298846,
 0.017844667273482717,
 -0.009114152020147438,
 0.032177154965092644,
 0.027633963663410383,
 -0.009760042113716427,
 -0.052590238743664655,
 0.004106602580975735,
 0.010110101202756735,
 -0.03459504745172303,
 -0.021276118017956525,
 -0.017985270733978233,
 -0.02472712478534688,
 -0.03362432781263222,
 -0.03138262110934655,
 -0.022238760021757262,
 0.024783330532918806,
 -0.05135904251818439,
 -0.0037180119837142574,
 0.01300372958345835,
 0.008986021887944482,
 0.019003673876013497,
 -0.025952082904245985,
 0.02153089613810564,
 -0.009281025613648816,
 0.04498459359884859,
 -0.011924590430159905,
 -0.004279509625004491,
 0.010242084333053408,
 0.0013480823232990841,
 0.013499949919409823,
 -0.00017229446739282933,
 0.015692873475282972,
 -0.0059294570821525165,
 0.02837933764169471,
 -0.0013834457354439883,
 0.0035785514407329975,
 -0.017566996863404398,
 -0.050225059615230785,
 -7.078818037836921e-05,
 0.03380418416848375,
 0.05923078804841329,
 -0.05059893024946009,
 -0.009436280648793687,
 -0.019711721033743128,
 -0.03127916968023874,
 -0.022560543484223258,
 -0.010576403742455286,
 0.007764098482320424,
 -0.023972565042393406,
 -0.009134104118710348,
 0.029178225953775744,
 -0.011857181884871398,
 -0.001356113121880328,
 -0.014962366758086102,
 0.046576150783233745,
 0.028795780468470655,
 -0.056407135237979855,
 0.013758203459112313,
 0.015306248322809931,
 -0.011400150977141506,
 -0.014680772925152607,
 0.03600805156258917,
 -0.0012056525026765547,
 -0.008583473442358562,
 0.02436099238996688,
 -0.026805463011873115,
 0.04192162047916043,
 0.01218601732658349,
 0.019457857587001862,
 0.009690733457454331,
 0.007517826315769618,
 -0.009578805262842119,
 -0.004069184123382034,
 -0.025047058537210738,
 -0.0007412354120253528,
 0.01240502560734989,
 0.018102939479989446,
 0.00518436005136385,
 -0.00929806348467315,
 0.012080329274931075,
 0.06860204984225786,
 0.01189201244460431,
 -0.04503988297603047,
 -0.03814447070202252,
 0.05559354427208515,
 0.0017062993148876993,
 0.02397964315516544,
 0.029732675858275392,
 0.02372604613463017,
 0.010970403809887804,
 -0.012136522804231135,
 -0.027776754533966594,
 -0.05482911827459879,
 0.08070853470389604,
 -0.21595322067472755,
 0.07332225675158248,
 -0.021295037672546646,
 -0.018812651377261,
 0.0010284102460910499,
 -0.0263466957519523,
 -0.031607469554367315,
 -0.029567272699853604,
 -0.06178123690592878,
 0.022446295854334896,
 0.053411130127000106,
 0.006168234357102037,
 0.029234582732763807,
 0.04948725078361098,
 -0.01358393526565789,
 -0.019716798404496885,
 0.006573386652181462,
 0.010028212308323238,
 -0.004885236052868699,
 -0.024662184670372015,
 -0.010925505733532652,
 0.0030150666332821197,
 0.01730937799504613,
 -0.012710938043754883,
 0.01743520074054658,
 0.012220618793718888,
 0.05648549508822234,
 0.034965045572563275,
 -0.03989879223750257,
 -0.03279742062738432,
 -0.014107170879500917,
 0.0042049528815789345,
 -0.016720711838371344,
 0.018045661239664723,
 -0.05766256436933034,
 -0.001680410324084808,
 -0.030859348161895048,
 -0.013699075508185447,
 -0.028295387932072924,
 0.02718152105616312,
 -0.03405903016792101,
 -0.02615632150040165,
 -0.002275109931286971,
 -0.018242049596145622,
 0.009071015411319825,
 -0.013202429908493702,
 0.04728543843495435,
 -0.020282843788395073,
 -0.030505814162396023,
 -0.017579366166687864,
 -0.020157430015605736,
 0.030584857896466637,
 0.018542717509049785,
 0.016900054857106214,
 -0.045466999820868284,
 -0.008405090745852817,
 -0.012415006917276176,
 0.01610923060445762,
 -0.05043479303976234,
 -0.01094989527086027,
 -0.006106751673669187,
 0.035337244679321846,
 0.009511767847561584,
 0.04173830737055977,
 -0.03719269956621931,
 -0.010263334113907561,
 0.019463943813675774,
 0.01571439290660931,
 0.0046342683365599895,
 -0.03215391309682945,
 0.013993361071021134,
 0.026496237217715206,
 -0.02995035625046732,
 0.04721908982475033,
 0.02454617217899171,
 0.03061382029173882,
 -0.028286953930520057,
 0.04100854223458597,
 -0.014354736825283897,
 -0.00036610040726545965,
 -0.028726916930640608,
 0.03533182621514513,
 -0.1333598410491465,
 -0.048573305381130374,
 0.003682218895675352,
 0.02339079202743044,
 0.07326499548107979,
 0.010074472552293377,
 -0.05149419527184131,
 0.019456486425381194,
 0.007868049502989033,
 0.017218767630274443,
 0.0377207020030728,
 -0.009584534444460356,
 0.016073129853545167,
 0.0034679019222113466,
 0.005862473291509621,
 -0.021930228293320704,
 -0.010729890352445582,
 -0.005436813305893762,
 0.008706431681899007,
 -0.03160014368219353,
 0.02006649892119753,
 -0.033587992029684544,
 -0.026226411956365034,
 -0.007363489178298781,
 0.014476753239701235,
 0.028316113175727884,
 -0.02482482174780162,
 0.015148379765372996,
 0.016540030749168776,
 -0.03169844646729502,
 0.03792345064885353,
 -0.24470955139790654,
 -0.015896388308528714,
 -0.003926902347486964,
 0.007641007538771643,
 0.049585952359530366,
 0.0003977244003355453,
 -0.02787340106443718,
 0.029177309583385696,
 -0.003083127159133324,
 -0.0013686157061460831,
 -0.025232984998405237,
 -0.04239696725521233,
 -0.058534012246481276,
 -0.009672569469039561,
 0.05658497897293768,
 0.20111315542406902,
 -0.036674839991997915,
 0.0034503849931108825,
 -0.03197929023409444,
 0.00968366501748086,
 -0.040219954604481974,
 -0.048358942589146865,
 -0.02286949097329974,
 -0.030824850210674073,
 0.03448613004293679,
 0.04369680131988953,
 0.06153910130319796,
 -0.02190717139611773,
 -0.027951407942381275,
 0.02150322344930834,
 -0.0303682466030631,
 0.03392613440059514,
 0.001856258577669183,
 -0.01880135965767694,
 0.01581441643166545,
 0.026480752255105565,
 -0.018372549224599737,
 -0.021711134314953015,
 0.020240066261001784,
 0.05084050075711707,
 0.018452784240177413,
 0.0323739675671245,
 -0.017909376598877865,
 0.06042234107263068,
 -0.02622293144586505,
 -0.014354080093171026,
 -0.015220990239909018,
 0.027528275611757972,
 0.02695547623868868,
 -0.048358817012463785,
 -0.008470890552012127,
 -0.12293819818061834,
 -0.0013167087878324564,
 0.0720563589370168,
 0.027263349538030158,
 0.02814126291737756,
 0.0003682676232379275,
 0.04468312810430864,
 -0.030641542193020038,
 0.009590805472496263,
 -0.010014237320478537,
 -0.0006147979177517529,
 -0.007249190129849646,
 0.01798989161651917,
 -0.01647305764951377,
 -0.015331791298941468,
 -0.016758600360035496,
 0.009339910047629435,
 0.00767994411664486,
 -0.002186435314115155,
 -0.028103722277065188,
 0.0504684849244365,
 0.03777436397432123,
 -0.005274669032096142,
 -0.05030626530462903,
 -0.02201401509265093,
 0.0051296196479249006,
 0.009491883288890385,
 0.03738868573791791,
 0.02139529368416471,
 -0.022682683778341473,
 0.0331828120737952,
 0.0046665011559353315,
 0.036154361974236056,
 0.01027899793844148,
 0.022358285266299426,
 0.004937448292220433,
 -0.025607693941843226,
 -0.01988893518830334,
 0.019229396266869217,
 0.022290952406417208,
 0.001884826254880766,
 0.004909912210490537,
 -0.04645302793641953,
 -0.023789974848211572,
 -0.024213597606691773,
 0.031780919802399506,
 -0.019836284618448365,
 0.022875671382485963,
 -0.012594524046385157,
 0.017889964819448642,
 -0.037249570530815124,
 -0.014145755163868626,
 -0.047132301063901594,
 -0.014324739270867394,
 -0.010703889021420799,
 0.016741034897244003,
 0.0376632116399726,
 0.026144257653914864,
 0.03969879439987419]

### IndexFlatL2 - Exact Search for L2

In [12]:
import faiss

index_l2 = faiss.IndexFlatL2(embedding_dimension)
index_l2.is_trained

True

In [13]:
index_l2.add(embeddings)
index_l2.ntotal

1000

In [14]:
_, document_indices = index_l2.search(np.expand_dims(xq, axis=0), k=4)
dataset.iloc[document_indices[0]]

,sentence,embedding,id
684,A man is punching a soccer ball,"[-0.01688985712826252, 0.029744451865553856, 0...",685
950,A soccer player is sitting on the field and is...,"[-0.011246275156736374, 0.009713653475046158, ...",951
352,An opponent is tackling a soccer player,"[0.0006955061689950526, -0.02708514593541622, ...",353
25,A group of men is playing soccer on the beach,"[0.004342387896031141, 0.04711844399571419, 0....",26

### IndexIVFFlat - Inverted file with exact post-verification

<img src='images/ivf.png' width="1000">

In [15]:
ncentroids = 20
quantizer = faiss.IndexFlatL2(embedding_dimension)
index_ivf = faiss.IndexIVFFlat(quantizer, embedding_dimension, ncentroids)
index_ivf.is_trained

False

In [16]:
index_ivf.train(embeddings)
index_ivf.is_trained

True

In [17]:
index_ivf.add(embeddings)
index_ivf.ntotal

1000

In [18]:
_, document_indices = index_ivf.search(np.expand_dims(xq, axis=0), k=4)
dataset.iloc[document_indices[0]]

,sentence,embedding,id
352,An opponent is tackling a soccer player,"[0.0006955061689950526, -0.02708514593541622, ...",353
979,The crowd is watching a football game,"[-0.01140331570059061, 0.015461748465895653, -...",980
551,A football player is running past an official ...,"[0.03300335630774498, 0.017781982198357582, -0...",552
172,Two men are playing table football,"[-0.03752468526363373, 0.05197532847523689, -0...",173

In [19]:
index_ivf.nprobe = 5
_, document_indices = index_ivf.search(np.expand_dims(xq, axis=0), k=4)
dataset.iloc[document_indices[0]]

,sentence,embedding,id
684,A man is punching a soccer ball,"[-0.01688985712826252, 0.029744451865553856, 0...",685
950,A soccer player is sitting on the field and is...,"[-0.011246275156736374, 0.009713653475046158, ...",951
352,An opponent is tackling a soccer player,"[0.0006955061689950526, -0.02708514593541622, ...",353
137,A group of boys is playing soccer on the seashore,"[0.023316802456974983, 0.0333450511097908, 0.0...",138

### IndexIVFPQ - IVF + Product Quantizer (PQ)

<img src='images/ivf-pq.png' width="1000">

In [20]:
code_size = 8
bits_per_centroid = 4

index_ivf_pq = faiss.IndexIVFPQ(
    quantizer, embedding_dimension, ncentroids, code_size, bits_per_centroid
)
index_ivf_pq.is_trained

False

In [21]:
index_ivf_pq.train(embeddings)
index_ivf_pq.add(embeddings)
index_ivf_pq.ntotal

1000

In [22]:
index_ivf_pq.nprobe = 5
_, document_indices = index_ivf_pq.search(np.expand_dims(xq, axis=0), k=4)
dataset.iloc[document_indices[0]]

,sentence,embedding,id
352,An opponent is tackling a soccer player,"[0.0006955061689950526, -0.02708514593541622, ...",353
551,A football player is running past an official ...,"[0.03300335630774498, 0.017781982198357582, -0...",552
979,The crowd is watching a football game,"[-0.01140331570059061, 0.015461748465895653, -...",980
469,A football player in a red and white uniform i...,"[-0.01379761379212141, -0.04831472039222717, 0...",470

## Pinecone

In [23]:
import os

from pinecone import Pinecone

PINECONE_API_KEY = os.environ.get("PINECONE_API_KEY")
database = Pinecone(api_key=PINECONE_API_KEY)

/Users/svpino/dev/llm/.venv/lib/python3.10/site-packages/pinecone/data/index.py:1: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

In [24]:
from pinecone import ServerlessSpec

serverless_spec = ServerlessSpec(cloud="aws", region="us-east-1")

In [25]:
import time

INDEX_NAME = "underfitted-random-sentences"

if INDEX_NAME not in database.list_indexes().names():
    database.create_index(
        name=INDEX_NAME,
        dimension=embedding_dimension,
        metric="cosine",
        spec=serverless_spec,
    )

    time.sleep(1)

pinecone_index = database.Index(INDEX_NAME)

In [26]:
pinecone_index.describe_index_stats()

{'dimension': 1536,
 'index_fullness': 0.0,
 'namespaces': {'': {'vector_count': 1000}},
 'total_vector_count': 1000}

In [285]:
def iterator(dataset, size):
    for i in range(0, len(dataset), size):
        yield dataset.iloc[i : i + size]


def vector(batch):
    vector = []
    for i in batch.to_dict("records"):
        vector.append((str(i["id"]), i["embedding"], {"sentence": i["sentence"]}))

    return vector

In [286]:
if pinecone_index.describe_index_stats()["total_vector_count"] == 0:
    for batch in iterator(dataset, 100):
        pinecone_index.upsert(vector(batch))

In [288]:
pinecone_index.describe_index_stats()

{'dimension': 1536,
 'index_fullness': 0.0,
 'namespaces': {'': {'vector_count': 1000}},
 'total_vector_count': 1000}

In [27]:
response = pinecone_index.query(vector=xq, top_k=4, include_metadata=True)
for match in response["matches"]:
    print(match["metadata"]["sentence"])

A man is punching a soccer ball
A soccer player is sitting on the field and is drinking water
An opponent is tackling a soccer player
A group of men is playing soccer on the beach

In [29]:
query2 = "I like animals that eat too much"
xq2 = get_embedding(query2)
response = pinecone_index.query(vector=xq2, top_k=5, include_metadata=True)
for match in response["matches"]:
    print(match["metadata"]["sentence"])

The animal with big eyes is voraciously eating
Some kittens are hungry
Someone is cleaning an animal
A lemur is eating quickly
A cat is eating corn on the cob

In [30]:
database.delete_index(INDEX_NAME)